name: animated_path
description: A Flutter package that is used to create trim path animation.
version: 0.0.1
homepage: https://github.com/himanshugarg08/animated_path
repository: https://github.com/himanshugarg08/animated_path

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
